# $Id: defaults/main.yml v.0.4 $ $Date: 2018/05/11 $ $Author: Filippo "joeyrs" Civiletti <fc@xafe.it> $
# Ansible task file for role fedora_provisioner.
---
- name: "Adding RPMFusion repositories."
  dnf:
    name: "{{ item.baseurl }}"
    state: present
  with_items:
    - "{{ repository_rpmfusion.free }}"
    - "{{ repository_rpmfusion.nonfree }}"
  loop_control:
    label: "{{ item.description }}"

- name: "Adding extra repositories."
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: yes
    enabled: yes
    gpgkey: "{{ item.gpgkey }}"
  with_items:
    - "{{ repository_extra.vscode }}"
    - "{{ repository_extra.opera }}"
    - "{{ repository_extra.docker }}"
  loop_control:
    label: "Repository: {{ item.description }}."

- name: "Importing package groups vars."
  include_vars:
    dir: vars
    extensions: [yml]

- name: "Installing per-group packages."
  dnf:
    name: "{{ item.pkgs }}"
    state: present
  with_items:
    - "{{ group_sysutils.archivers }}"
    - "{{ group_sysutils.editors }}"
    - "{{ group_sysutils.iofs_utils }}"
    - "{{ group_sysutils.net_utils }}"
    - "{{ group_sysutils.misc_utils }}"
    - "{{ group_sysutils.multiplexers }}"
    - "{{ group_fonts }}"
    - "{{ group_development }}"
    - "{{ group_desktop.browsers }}"
    - "{{ group_desktop.im }}"
    - "{{ group_desktop.misc }}"
    - "{{ group_kdespecific }}"
    - "{{ group_gnomespecific }}"
  loop_control:
    label: "{{ item.description }}: {{ item.pkgs }}"
...